get_hello_world2:
  name: get_hello_world2    
  description: "Returns Hello World 2"
  fields:
    currency:
      description: "What currecy should the prices be returned in"
      example: "NOK" 

test_service:
  name: test_service
  description: "A test service that returns a static message."
  fields:
    message:
      description: "The message to return."
      example: "Hello, World!"